### ISSUE TITLE
So stupid

### ISSUE THREAD

**Issue by jintian93** [HaveTwoBrush/chatbot#1]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/48214524/57007763-ad5e4a80-6c1d-11e9-9fec-68085bfb803b.png">

I have nothing to say.....

**Comment by Ailln** [comment]
This is not an open-domain chatbot, but a **task-oriented** chatbot. 

There is no training on large-scale datasets, only a few data for my cat named "锅贴".

So, it seems stupid.
